# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-19 08:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(db_index=True)),
                ('video_name', models.CharField(max_length=100)),
                ('video_desc', models.TextField()),
            ],
        ),
    ]
