# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-17 11:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.IntegerField(db_index=True, unique=True)),
                ('type', models.CharField(default='normal', max_length=100)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
