# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('create_time', models.DateField(auto_created=True, auto_now_add=True)),
                ('case_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('case_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func_id', models.IntegerField(db_index=True, unique=True)),
                ('func_name', models.CharField(max_length=100)),
                ('func_desc', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField()),
                ('step_name', models.CharField(max_length=100)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_step', to='regressplatform.Case')),
                ('func_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regressplatform.Function')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('task_name', models.CharField(max_length=1000)),
                ('task_type', models.IntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateField()),
                ('status', models.IntegerField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_case', to='regressplatform.Task'),
        ),
    ]
