# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regressplatform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(),
        ),
    ]
