# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-09 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regressplatform', '0002_auto_20181009_1405'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projcet',
            fields=[
                ('project_id', models.IntegerField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='proj_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='regressplatform.Projcet'),
            preserve_default=False,
        ),
    ]
